### ISSUE TITLE
Role name issue

### ISSUE THREAD

**Issue by StarSheep57** [MinnDevelopment/strumbot#16]
I wanted to use `Star-notify` other than `live` for the live role, so I have changed the config file into this:
 
![image](https://user-images.githubusercontent.com/125167856/218289544-5913265f-35a4-4b2c-b916-008d2026b1a0.png)

But when I want to use the command `/notify role: live` I can't:

![image](https://user-images.githubusercontent.com/125167856/218290326-08362f51-33c4-4cd2-9a46-1396cdde8928.png)

When I use instead the commend `/notify role: Star-notify` I get this message:

The application did not respond

![image](https://user-images.githubusercontent.com/125167856/218289801-84fbccc1-803b-42d3-8aba-53619bc0c990.png)

But when I add in the config the role `live` as one of the other `role_name` I can yous the command `/notify role: live` and I geht the role `Star-notify` and when I go live I get the Notification with `Star-notify`.

![image](https://user-images.githubusercontent.com/125167856/218289888-0f4eab7a-3a1b-4c43-aea1-0d7fc1a1f2ff.png)
![image](https://user-images.githubusercontent.com/125167856/218290203-4ab12810-3e02-49dc-9ef4-a8ce73a67426.png)

Have I done something wrong or is this a bug?

**Comment by MinnDevelopment** [comment]
Should be fixed in [1.3.6](https://github.com/MinnDevelopment/strumbot/releases/tag/1.3.6)
