### ISSUE TITLE
[Feature Request] Possible to have streamers in separate channels?

### ISSUE THREAD

**Issue by Ufinexa** [MinnDevelopment/strumbot#18]
So for example a streamers discord that has just their notifications in one channel, and then a self promo channel for other streamers notifications to go, would be nice to split them up rather than having to setup more than one bot for the job.

**Comment by MinnDevelopment** [comment]
No, setting up multiple bots is the intended way to do this. Your users will also want separate notification roles for each channel either way, which is achieved through multiple bots.
