### ISSUE TITLE
Thumbnails very intermittent

### ISSUE THREAD

**Issue by Ufinexa** [MinnDevelopment/strumbot#19]
Only just started recently where it has been very hit and miss with thumbnails showing when someone goes live, I'd say it's an 80/20 for the thumbnail to not display at all, not sure if it's an API thing or not. Beforehand it used to be very consistent in delivering them.

**Comment by MinnDevelopment** [comment]
This is unfortunately just twitch being inconsistent. However, usually the start thumbnails are less interesting regardless.

**Comment by Ufinexa** [comment]
Understood, thank you!
